global using PsychologyApp.Application.Models;
global using PsychologyApp.Application.Models.Tests;
global using TestQuestion = PsychologyApp.Application.Models.Tests.Question;
global using PsychologyApp.Application.Tests;
global using PsychologyApp.Domain.Tests;
global using TechniqueId = PsychologyApp.Domain.Practice.TechniqueId;
global using TechniqueUiKind = PsychologyApp.Domain.Practice.TechniqueUiKind;
global using PsychologyApp.Presentation.App;
global using PsychologyApp.Presentation.App.Routes;
global using PsychologyApp.Presentation.Common;
global using PsychologyApp.Presentation.UI.Components;
global using PsychologyApp.Presentation.Models.Practice.Techniques;
global using PsychologyApp.Presentation.Shared.Common;
global using PsychologyApp.Presentation.Shared.Common.Infrastructure;
global using PsychologyApp.Presentation.Shared.Navigation;
global using PsychologyApp.Presentation.Entities.FilterChip;
global using PsychologyApp.Presentation.Entities.Quote;
global using PsychologyApp.Presentation.Pages.FindProblem;
global using PsychologyApp.Presentation.Pages.Question;
global using PsychologyApp.Presentation.Pages.TestHistory;
global using PsychologyApp.Presentation.Pages.TestsList;
global using PsychologyApp.Presentation.Features.RunTechniqueSession.Polarity;
global using PsychologyApp.Presentation.Features.RunTechniqueSession.PaperList;
global using PsychologyApp.Presentation.Pages.LuscherTest;
global using PsychologyApp.Presentation.Pages.TestResult;
global using PsychologyApp.Presentation.Pages.ProfileSettings;
global using PsychologyApp.Presentation.Features.SendReviewForm;
global using BaseViewModel = PsychologyApp.Presentation.Shared.ViewModels.BaseViewModel;
